name: Push component to https://components.espressif.com
on:
  push:
    tags:
      - v*
jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lvgl_esp32_drivers separately
        uses: actions/checkout@v3
        with:
          repository: zhw990217/lvgl_esp32_drivers
          path: lvgl_esp32_drivers
          submodules: "recursive"

      - name: Upload component to the component registry
        uses: espressif/upload-components-ci-action@v2.1.1
        with:
          components: "lvgl_esp32_drivers"
          version: ${{ github.ref_name }}
          namespace: "zhw990217"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
